# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Vt3_5qZwB8q39YhS28DHHXY7MFi7IcG
"""

# Step 1: Install necessary libraries (if not already installed)
# This only needs to be done once per Colab session.
!pip install transformers==4.37.2 pandas==2.2.0 torch==2.2.0

# Step 2: Load a pre-trained sentiment analysis model
from transformers import pipeline
import pandas as pd

# Load a sentiment analysis model from Hugging Face.
# A common sentiment analysis model is 'distilbert-base-uncased-finetuned-sst-2-english'
sentiment_analyzer = pipeline("sentiment-analysis")

# Step 3: Load Data
# Create a sample DataFrame of restaurant reviews.
data = {
    "review": [
        "The food was absolutely delicious, and the service was top-notch!",
        "I was extremely disappointed with my meal. It was cold and bland.",
        "The restaurant was okay, nothing special.",
        "I loved everything about this place! Will definitely come back.",
        "Terrible experience. The staff was rude, and the food took forever.",
    ]
}
df = pd.DataFrame(data)

# Step 4: Define a Sentiment Analysis Function
def analyze_sentiment(text):
    """Analyzes the sentiment of a given text using a pre-trained model.

    Args:
      text: The text to analyze.

    Returns:
      A string representing the sentiment: "positive", "negative", or "neutral".
    """
    result = sentiment_analyzer(text)[0]
    label = result["label"]
    if label == "POSITIVE":
        return "positive"
    elif label == "NEGATIVE":
        return "negative"
    else:
        return "neutral"


# Step 5: Analyze Sentiment on the Data
# Create a new column to store sentiment labels.
df["sentiment"] = df["review"].apply(analyze_sentiment)

# Display the DataFrame with sentiment labels.
print(df)

# Step 6: Analyze Results
# Count the number of reviews with each sentiment.
sentiment_counts = df["sentiment"].value_counts()

# Print the sentiment counts.
print(sentiment_counts)

# Plot the results.
sentiment_counts.plot(kind="bar")

import numpy as np
import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/Restaurant_Reviews.tsv', delimiter='\t' , quoting=3)

# @title Default title text